/*
 * JS for Account generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '351f0d08-2bfd-48a4-9124-1ad2de14b806';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Products",
    "location": "Products.html"
}];

function Account_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'Account_mobilenavbar_6',
        'home_item': 'Account_home_item',
        'products_item': 'Account_products_item',
        'account_item': 'Account_account_item',
        'mobileworkarea_10': 'Account_mobileworkarea_10',
        'mobiletextinput_11': 'Account_mobiletextinput_11',
        'mobiletextinput_12': 'Account_mobiletextinput_12',
        'mobilebutton_13': 'Account_mobilebutton_13'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Account';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Account_onLoad = function() {
            Account_elementsExtraJS();

            Account_deviceEvents();
            Account_windowEvents();
            Account_elementsEvents();
        };

    // screen window events


    function Account_windowEvents() {

        $('#Account').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Account_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Account_elementsExtraJS() {
        // screen (Account) extra code

    };

    // screen elements handler


    function Account_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Account_mobileheader1 [name="home_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Account_mobileheader1 [name="home_item"]');
        $(document).off("click", '#Account_mobileheader1 [name="products_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Products', {
                        reverse: false
                    });

                }
            },
        }, '#Account_mobileheader1 [name="products_item"]');
        $(document).off("click", '#Account_mobileheader1 [name="account_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Account', {
                        reverse: false
                    });

                }
            },
        }, '#Account_mobileheader1 [name="account_item"]');

    };

    $(document).off("pagebeforeshow", "#Account").on("pagebeforeshow", "#Account", function(event, ui) {
        Apperyio.CurrentScreen = "Account";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Account_onLoad();
};

$(document).off("pagecreate", "#Account").on("pagecreate", "#Account", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Account_js();
});