/*
 * JS for Products generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '351f0d08-2bfd-48a4-9124-1ad2de14b806';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Products",
    "location": "Products.html"
}];

function Products_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'Products_mobilenavbar_6',
        'home_item': 'Products_home_item',
        'products_item': 'Products_products_item',
        'account_item': 'Products_account_item',
        'mobileworkarea_10': 'Products_mobileworkarea_10',
        'mobilelist_11': 'Products_mobilelist_11',
        'mobilelistitem_14': 'Products_mobilelistitem_14',
        'mobilelistitembutton_15': 'Products_mobilelistitembutton_15',
        'mobilelistitem_18': 'Products_mobilelistitem_18',
        'mobilelistitembutton_19': 'Products_mobilelistitembutton_19',
        'mobilelistitem_20': 'Products_mobilelistitem_20',
        'mobilelistitembutton_21': 'Products_mobilelistitembutton_21'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Products';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Products_onLoad = function() {
            Products_elementsExtraJS();

            Products_deviceEvents();
            Products_windowEvents();
            Products_elementsEvents();
        };

    // screen window events


    function Products_windowEvents() {

        $('#Products').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Products_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Products_elementsExtraJS() {
        // screen (Products) extra code

        /* mobilelist_11 */

        listView = $("#Products_mobilelist_11");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Products_mobilelist_11 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_14 */

        /* mobilelistitem_18 */

        /* mobilelistitem_20 */

    };

    // screen elements handler


    function Products_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Products_mobileheader1 [name="home_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Products_mobileheader1 [name="home_item"]');
        $(document).off("click", '#Products_mobileheader1 [name="products_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Products', {
                        reverse: false
                    });

                }
            },
        }, '#Products_mobileheader1 [name="products_item"]');
        $(document).off("click", '#Products_mobileheader1 [name="account_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Account', {
                        reverse: false
                    });

                }
            },
        }, '#Products_mobileheader1 [name="account_item"]');

    };

    $(document).off("pagebeforeshow", "#Products").on("pagebeforeshow", "#Products", function(event, ui) {
        Apperyio.CurrentScreen = "Products";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Products_onLoad();
};

$(document).off("pagecreate", "#Products").on("pagecreate", "#Products", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Products_js();
});